# Generated by Django 5.0.1 on 2024-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_menuitem_menu_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
