# Generated by Django 5.0.1 on 2024-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_menuitem_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parents',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
